module WavesUtilities
  class Nationality
    class << self
      def all
        raw_list.map(&:first)
      end

      private

      def raw_list
        [
          ['AKROTIRI AND DHEKELIA','British Overseas Territory (British Dependent Territory)'],
          ['ANGUILLA','British Overseas Territory (British Dependent Territory)'],
          ['ANTIGUA BRD','Commonwealth Citizen'],
          ['AUSTRALIA','Commonwealth Citizen'],
          ['AUSTRIA','European Union Country'],
          ['BAHAMAS','Commonwealth Citizen'],
          ['BANGLADESH','Commonwealth Citizen'],
          ['BARBADOS','Commonwealth Citizen'],
          ['BELGIUM','European Union Country'],
          ['BELIZE','Commonwealth Citizen'],
          ['BERMUDA','British Overseas Territory (British Dependent Territory)'],
          ['BOTSWANA','Commonwealth Citizen'],
          ['BRITISH ANTARCTIC TERRITORY *','British Overseas Territory (British Dependent Territory)'],
          ['BRITISH INDIAN OCEAN TERRITORY *','British Overseas Territory (British Dependent Territory)'],
          ['BRITISH VIRGIN ISLANDS','British Overseas Territory (British Dependent Territory)'],
          ['BRUNEI','Commonwealth Citizen'],
          ['BULGARIA','European Union Country'],
          ['CAMEROON','Commonwealth Citizen'],
          ['CANADA','Commonwealth Citizen'],
          ['CAYMAN ISLANDS','British Overseas Territory (British Dependent Territory)'],
          ['CHANNEL ISLANDS','British Citizen'],
          ['CROATIA','European Union Country'],
          ['CYPRUS','European Union Country'],
          ['CZECH REPUBLIC','European Union Country'],
          ['DENMARK','European Union Country'],
          ['DOMINICA','Commonwealth Citizen'],
          ['EIRE','European Union Country'],
          ['ESTONIA','European Union Country'],
          ['FALKLAND ISLANDS *','British Overseas Territory (British Dependent Territory)'],
          ['FIJI','Commonwealth Citizen'],
          ['FINLAND','European Union Country'],
          ['FRANCE','European Union Country'],
          ['GAMBIA','Commonwealth Citizen'],
          ['GERMANY','European Union Country'],
          ['GHANA','Commonwealth Citizen'],
          ['GIBRALTAR','British Overseas Territory (British Dependent Territory)'],
          ['GREECE','European Union Country'],
          ['GRENADA','Commonwealth Citizen'],
          ['GUYANA','Commonwealth Citizen'],
          ['HONG KONG','British National Overseas'],
          ['HUNGARY','European Union Country'],
          ['ICELAND','European Economic Area Country'],
          ['INDIA','Commonwealth Citizen'],
          ['ISLE OF MAN','British Citizen'],
          ['ITALY','European Union Country'],
          ['JAMAICA','Commonwealth Citizen'],
          ['KENYA','Commonwealth Citizen'],
          ['KIRIBATI','Commonwealth Citizen'],
          ['LATVIA','European Union Country'],
          ['LESOTHO','Commonwealth Citizen'],
          ['LIECHTENSTEIN','European Economic Area Country'],
          ['LITHUANIA','European Union Country'],
          ['LUXEMBOURG','European Union Country'],
          ['MALAWI','Commonwealth Citizen'],
          ['MALAYSIA','Commonwealth Citizen'],
          ['MALDIVES','Commonwealth Citizen'],
          ['MALTA','European Union Country'],
          ['MAURITIUS','Commonwealth Citizen'],
          ['MONTSERRAT *','British Overseas Territory (British Dependent Territory)'],
          ['MOZAMBIQUE','Commonwealth Citizen'],
          ['NAMIBIA','Commonwealth Citizen'],
          ['NAURU','Commonwealth Citizen'],
          ['NETHERLANDS','European Union Country'],
          ['NEW ZEALAND','Commonwealth Citizen'],
          ['NIGERIA','Commonwealth Citizen'],
          ['NORWAY','European Economic Area Country'],
          ['PAKISTAN','Commonwealth Citizen'],
          ['PAPUA NEW GUINEA','Commonwealth Citizen'],
          ['PITCAIRN ISLANDS *','British Overseas Territory (British Dependent Territory)'],
          ['POLAND','European Union Country'],
          ['PORTUGAL','European Union Country'],
          ['ROMANIA','European Union Country'],
          ["SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA *",'British Overseas Territory (British Dependent Territory)'],
          ['SAINT KITTS AND NEVIS','Commonwealth Citizen'],
          ['SAINT LUCIA','Commonwealth Citizen'],
          ['SAINT VINCENT AND THE GRENADINES','Commonwealth Citizen'],
          ['SAMOA (WESTERN SOMOA)','Commonwealth Citizen'],
          ['SEYCHELLES','Commonwealth Citizen'],
          ['SIERRA LEONE','Commonwealth Citizen'],
          ['SINGAPORE','Commonwealth Citizen'],
          ['SLOVAKIA','European Union Country'],
          ['SLOVENIA','European Union Country'],
          ['SOLOMON ISLANDS','Commonwealth Citizen'],
          ['SOUTH AFRICA','Commonwealth Citizen'],
          ['SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS *','British Overseas Territory (British Dependent Territory)'],
          ['SPAIN','European Union Country'],
          ['SRI LANKA','Commonwealth Citizen'],
          ['SWAZILAND','Commonwealth Citizen'],
          ['SWEDEN','European Union Country'],
          ['SWITZERLAND','European Economic Area Country'],
          ['TANZANIA','Commonwealth Citizen'],
          ['TONGA','Commonwealth Citizen'],
          ['TRINIDAD & TOBAGO','Commonwealth Citizen'],
          ['TURKEY','European Economic Area Country'],
          ['TURKS AND CAICOS ISLANDS *','British Overseas Territory (British Dependent Territory)'],
          ['TUVALU','Commonwealth Citizen'],
          ['UGANDA','Commonwealth Citizen'],
          ['UNITED KINGDOM','British Citizen'],
          ['VANUATA','Commonwealth Citizen'],
          ['ZAMBIA','Commonwealth Citizen'],
          ['ZIMBABWE','Commonwealth Citizen']
        ]
      end
    end
  end
end
